### ISSUE TITLE
I got NullPointerException after load bert model

### ISSUE THREAD

**Issue by SmartMapple** [cyk1337/BERT-Text-Classification-J#1]
my Exception:
> Starting to predict!
====================== Start loading models ... ====================== 
====================== Models loaded! ======================
java.lang.NullPointerException
	at com.google.common.io.ByteStreams.copy(ByteStreams.java:167)
	at com.google.common.io.ByteStreams.toByteArray(ByteStreams.java:210)
	at model.BaseModel.<init>(BaseModel.java:21)
	at model.Bert.<init>(Bert.java:10)
	at EnsembleDemo._load_Bert(EnsembleDemo.java:56)
	at EnsembleDemo.loadModels(EnsembleDemo.java:50)
	at EnsembleDemo.<init>(EnsembleDemo.java:21)
	at EnsembleDemo.main(EnsembleDemo.java:164)
Exception in thread "main" java.lang.NullPointerException
	at model.Bert.predict_single_case(Bert.java:21)
	at EnsembleDemo.__pred_with_Bert(EnsembleDemo.java:79)
	at EnsembleDemo.doPredictWithModels(EnsembleDemo.java:63)
	at EnsembleDemo.main(EnsembleDemo.java:174)

Is this Exception because of the pb file?
**how to generate the pb file correctly?**  i generate it through the code:

> frozen_graph = convert_variables_to_constants(sess, input_graph_def, output_names)

i don't know how auther generate it.
and or other problem cause the Exception.

**Comment by cyk1337** [comment]
Hi @SmartMapple, you may find the solution to exporting the Google BERT into a pb file by checking another repository at https://github.com/cyk1337/BERT-Classification/blob/ad97db6c2bedad22ee2685943aae64e35d81512d/bert/run_classification.py#L1138
